# # -*- coding: utf-8 -*-
# """visualize_tech_jobs.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1ISRAhEQ97U1jiqIGRv9gaf8_zJwiov_d

# # 📊 Tech Jobs Dataset — Stage 3: Visualizations

# Now that we've explored the raw data, it's time to **see** it. Charts reveal patterns that numbers alone can't show — skewed distributions, outliers, clear category gaps.

# This notebook covers **10 visualizations** grouped by what they answer:

# | # | Chart | Question answered |
# |---|-------|------------------|
# | 1 | Salary histogram | What does the salary distribution look like? |
# | 2 | Salary by experience (boxplot) | Does seniority actually pay more? |
# | 3 | Salary by work mode (boxplot) | Do remote workers earn more? |
# | 4 | Top countries by job count (bar) | Where are the most jobs? |
# | 5 | Average salary by country (bar) | Where does the highest pay come from? |
# | 6 | Job role distribution (horizontal bar) | Which roles dominate? |
# | 7 | Salary by company size (boxplot) | Does company size affect pay? |
# | 8 | Records per year (line) | How has hiring changed over time? |
# | 9 | Work mode breakdown (pie) | Remote vs hybrid vs onsite split? |
# | 10 | Correlation heatmap | Which numeric columns move together? |

# ---
# ## Setup — imports and global style

# We set a consistent style once here so every chart looks clean without repeating styling code.

# - `figsize` controls default chart size (width, height in inches)
# - `rcParams` sets font sizes globally so axis labels never overlap titles
# - `tight_layout()` is called on every chart to auto-fix overlapping elements
# """

# import pandas as pd
# import matplotlib.pyplot as plt
# import matplotlib.ticker as mticker
# import seaborn as sns

# # ── Load data ──────────────────────────────────────────────
# url = 'https://drive.google.com/uc?export=download&id=14S87aEIRTfnTpPa_VUZxdAtcuQFkktTS'
# df = pd.read_csv(url)

# # ── Global style ───────────────────────────────────────────
# sns.set_theme(style='whitegrid', palette='muted')

# plt.rcParams.update({
#     'figure.figsize'     : (12, 5),   # default chart size
#     'figure.dpi'         : 120,        # sharp rendering
#     'axes.titlesize'     : 14,         # chart title font size
#     'axes.titlepad'      : 14,         # gap between title and chart
#     'axes.labelsize'     : 11,         # axis label font size
#     'axes.labelpad'      : 8,          # gap between axis label and ticks
#     'xtick.labelsize'    : 9,          # x-axis tick font size
#     'ytick.labelsize'    : 9,          # y-axis tick font size
#     'legend.fontsize'    : 9,
#     'figure.titlesize'   : 15,
# })

# # Ordered categories for experience level (used in multiple charts)
# EXP_ORDER = ['Entry', 'Mid', 'Senior', 'Lead']
# COMP_SIZE = ['Startup', 'Small', 'Medium', 'Large', 'Enterprise']
# JOB_ROLE =

# print('Setup complete — ready to plot!')

# """---
# ## Chart 1 — Salary distribution (histogram)

# A histogram groups salaries into buckets and shows how many records fall in each. This reveals:
# - Whether most jobs cluster around a common salary
# - Whether the distribution is symmetric or skewed right (long tail of very high earners)
# - Any unusual gaps or spikes

# The vertical dashed lines mark the **mean** and **median** — if they're far apart, the data is skewed.
# """

# fig, ax = plt.subplots(figsize=(12, 5))

# ax.hist(df['salary_usd'], bins=60, color='steelblue', edgecolor='white', linewidth=0.4)

# # Mean and median reference lines
# mean_sal   = df['salary_usd'].mean()
# median_sal = df['salary_usd'].median()

# ax.axvline(mean_sal,   color='tomato',      linestyle='--', linewidth=1.5, label=f'Mean   ${mean_sal:,.0f}')
# ax.axvline(median_sal, color='darkorange',  linestyle='--', linewidth=1.5, label=f'Median ${median_sal:,.0f}')

# ax.set_title('Salary Distribution Across All Tech Jobs')
# ax.set_xlabel('Salary (USD)')
# ax.set_ylabel('Number of Jobs')
# ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
# ax.legend(framealpha=0.9)

# plt.tight_layout()
# # plt.savefig('chart1_salary_distribution.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 2 — Salary by experience level (boxplot)

# A boxplot summarises the full salary range at each experience level in one shape:

# ```
#    ──┬──         ← max (excluding outliers)
#      │
#   ┌──┴──┐
#   │     │        ← 75th percentile (top of box)
#   │─────│        ← median (line in the middle)
#   │     │        ← 25th percentile (bottom of box)
#   └──┬──┘
#      │
#    ──┴──         ← min (excluding outliers)
#      ○           ← outlier dots
# ```

# The categories are ordered Entry → Executive so the progression is easy to read.
# """

# # Filter to only experience levels that actually exist in the data
# exp_order_present = [e for e in EXP_ORDER if e in df['experience_level']]

# fig, ax = plt.subplots(figsize=(10, 5))

# sns.boxplot(
#     data=df,
#     x='experience_level',
#     y='salary_usd',
#     order=exp_order_present,
#     palette='Blues',
#     width=0.5,
#     flierprops=dict(marker='o', markersize=2, alpha=0.3),
#     ax=ax
# )

# ax.set_title('Salary by Experience Level')
# ax.set_xlabel('Experience Level')
# ax.set_ylabel('Salary (USD)')
# ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

# plt.tight_layout()
# # plt.savefig('chart2_salary_by_experience.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 3 — Salary by work mode (boxplot)

# One of the most asked questions in modern tech hiring: **do remote workers earn more?**

# This chart compares salary distributions across Remote, Hybrid, and Onsite roles side by side.
# The overlaid strip plot (small dots) shows the actual data points behind the boxes.
# """

# fig, ax = plt.subplots(figsize=(9, 5))

# sns.boxplot(
#     data=df,
#     x='work_mode',
#     y='salary_usd',
#     palette='Set2',
#     width=0.45,
#     flierprops=dict(marker='o', markersize=1.5, alpha=0.2),
#     ax=ax
# )

# ax.set_title('Salary by Work Mode (Remote vs Hybrid vs Onsite)')
# ax.set_xlabel('Work Mode')
# ax.set_ylabel('Salary (USD)')
# ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

# plt.tight_layout()
# # plt.savefig('chart3_salary_by_workmode.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 4 — Top 5 countries by job count (bar chart)

# Which countries contribute the most records to this dataset?

# - Bars are sorted from highest to lowest
# - Country names are rotated 45° to prevent overlapping
# - `ha='right'` aligns rotated labels cleanly under their bars
# """

# top_countries = df['country'].value_counts().head()

# fig, ax = plt.subplots(figsize=(10, 5))

# bars = ax.bar(
#     top_countries.index,
#     top_countries.values,
#     color=sns.color_palette('muted', 5),
#     edgecolor='white',
#     linewidth=0.5
# )

# # Add value labels on top of each bar
# for bar in bars:
#     h = bar.get_height()
#     ax.text(
#         bar.get_x() + bar.get_width() / 2,
#         h + 50,
#         f'{h:,}',
#         ha='center', va='bottom', fontsize=7.5
#     )

# ax.set_title('Top 5 Countries by Number of Job Records')
# ax.set_xlabel('Country')
# ax.set_ylabel('Number of Jobs')

# # Rotate labels 45° so they don't overlap
# ax.set_xticklabels(top_countries.index, rotation=45, ha='right', fontsize=9)

# # Add breathing room at the top so value labels don't clip
# ax.set_ylim(0, top_countries.max() * 1.12)

# plt.tight_layout()
# # plt.savefig('chart4_jobs_by_country.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 5 — Average salary by country, top 10 (horizontal bar)

# Job count (Chart 4) and average pay are different stories. A country might have few jobs but very high salaries — or many jobs but lower pay.

# We use a **horizontal bar chart** here because country names are long — placing them on the y-axis avoids any rotation and keeps the chart clean.
# """

# -avg_salary_country = (
#     df.groupby('country')['salary_usd']
#     .mean()
#     .sort_values(ascending=False)
#     .head(10)
# )

# fig, ax = plt.subplots(figsize=(11, 6))

# colors = sns.color_palette('Blues_r', len(avg_salary_country))
# bars = ax.barh(
#     avg_salary_country.index[::-1],   # reverse so highest is at top
#     avg_salary_country.values[::-1],
#     color=colors,
#     edgecolor='white',
#     linewidth=0.4
# )

# # Value labels at end of each bar
# for bar, val in zip(bars, avg_salary_country.values[::-1]):
#     ax.text(
#         val + 400,
#         bar.get_y() + bar.get_height() / 2,
#         f'${val:,.0f}',
#         va='center', fontsize=8
#     )

# ax.set_title('Top 10 Countries by Average Salary (USD)')
# ax.set_xlabel('Average Salary (USD)')
# ax.set_ylabel('')   # country names on y-axis are self-explanatory
# ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
# ax.set_xlim(0, avg_salary_country.max() * 1.12)

# plt.tight_layout()
# # plt.savefig('chart5_avg_salary_by_country.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 6 — Job role distribution (horizontal bar)

# How are jobs distributed across roles like Data Scientist, ML Engineer, Software Engineer?

# Job role names are often long, so a **horizontal bar chart** is the cleanest choice — the role names sit on the y-axis where there's plenty of space, no rotation needed.
# """

# role_counts = df['job_role'].value_counts().sort_values(ascending=True)

# fig, ax = plt.subplots(figsize=(11, max(5, len(role_counts) * 0.45)))

# colors = sns.color_palette('viridis', len(role_counts))
# bars = ax.barh(
#     role_counts.index,
#     role_counts.values,
#     color=colors,
#     edgecolor='white',
#     linewidth=0.4
# )

# # Count labels at end of each bar
# for bar, val in zip(bars, role_counts.values):
#     ax.text(
#         val + 30,
#         bar.get_y() + bar.get_height() / 2,
#         f'{val:,}',
#         va='center', fontsize=8
#     )

# ax.set_title('Job Count by Role')
# ax.set_xlabel('Number of Job Records')
# ax.set_ylabel('')
# ax.set_xlim(0, role_counts.max() * 1.10)

# # Increase left margin so role names don't clip
# plt.subplots_adjust(left=0.28)

# plt.tight_layout()
# # plt.savefig('chart6_job_role_distribution.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 7 — Salary by company size (boxplot)

# Do large corporations pay more than startups? This boxplot compares salary ranges across Small, Medium, and Large companies.

# The colour gradient (light → dark) reinforces the size ordering visually.
# """

# # Define a sensible size order
# size_order = [s for s in ['Small', 'Medium', 'Large'] if s in df['company_size'].unique()]

# fig, ax = plt.subplots(figsize=(9, 5))

# sns.boxplot(
#     data=df,
#     x='company_size',
#     y='salary_usd',
#     order=size_order,
#     palette='Purples',
#     width=0.45,
#     flierprops=dict(marker='o', markersize=1.5, alpha=0.2),
#     ax=ax
# )

# ax.set_title('Salary by Company Size')
# ax.set_xlabel('Company Size')
# ax.set_ylabel('Salary (USD)')
# ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
# ax.yaxis.set_major_locator(mticker.MultipleLocator(10000))

# plt.tight_layout()
# # plt.savefig('chart7_salary_by_company_size.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 8 — Hiring trends over time (line chart)

# How has the number of tech job records changed from 2020 to 2026?

# A second line shows average salary per year — plotted on a separate right-hand y-axis so both trends are readable on their own scale without one squashing the other.
# """

# yearly = df.groupby('year').agg(
#     job_count  =('id', 'count'),
#     avg_salary =('salary_usd', 'mean')
# ).reset_index()

# fig, ax1 = plt.subplots(figsize=(11, 5))

# # Left axis — job count
# color1 = 'steelblue'
# ax1.plot(yearly['year'], yearly['job_count'], color=color1, marker='o',
#          linewidth=2, markersize=6, label='Job count')
# ax1.fill_between(yearly['year'], yearly['job_count'], alpha=0.12, color=color1)
# ax1.set_xlabel('Year')
# ax1.set_ylabel('Number of Job Records', color=color1, labelpad=8)
# ax1.tick_params(axis='y', labelcolor=color1)
# ax1.set_xticks(yearly['year'])

# # Right axis — average salary (separate scale)
# ax2 = ax1.twinx()
# color2 = 'tomato'
# ax2.plot(yearly['year'], yearly['avg_salary'], color=color2, marker='s',
#          linewidth=2, markersize=6, linestyle='--', label='Avg salary')
# ax2.set_ylabel('Average Salary (USD)', color=color2, labelpad=8)
# ax2.tick_params(axis='y', labelcolor=color2)
# ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

# # Combine legends from both axes
# lines1, labels1 = ax1.get_legend_handles_labels()
# lines2, labels2 = ax2.get_legend_handles_labels()
# ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left', framealpha=0.9)

# ax1.set_title('Tech Job Count and Average Salary by Year (2020–2026)')

# plt.tight_layout()
# # plt.savefig('chart8_trends_over_time.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 9 — Work mode breakdown (donut chart)

# What percentage of jobs are Remote vs Hybrid vs Onsite?

# A donut chart (pie with a hole) is cleaner than a full pie — the hole adds visual breathing room and makes the slice labels easier to read. Percentages are shown on each slice; labels sit slightly outside to avoid crowding.
# """

# work_mode_counts = df['work_mode'].value_counts()

# fig, ax = plt.subplots(figsize=(7, 6))

# wedge_props = dict(width=0.45, edgecolor='white', linewidth=2)

# wedges, texts, autotexts = ax.pie(
#     work_mode_counts.values,
#     labels=work_mode_counts.index,
#     autopct='%1.1f%%',
#     startangle=90,
#     colors=sns.color_palette('Set2', len(work_mode_counts)),
#     wedgeprops=wedge_props,
#     pctdistance=0.78,    # % label sits inside the ring
#     labeldistance=1.12   # category label sits outside the ring
# )

# # Style the text so nothing overlaps
# for text in texts:
#     text.set_fontsize(10)
# for autotext in autotexts:
#     autotext.set_fontsize(9)
#     autotext.set_color('white')
#     autotext.set_fontweight('bold')

# ax.set_title('Work Mode Distribution\n(Remote vs Hybrid vs Onsite)', pad=18)

# plt.tight_layout()
# # plt.savefig('chart9_work_mode_donut.png', bbox_inches='tight')
# plt.show()

# """---
# ## Chart 10 — Correlation heatmap

# A heatmap shows how pairs of numeric columns **move together**:

# - **+1.0 (dark blue)** → as one goes up, the other goes up perfectly
# - **0.0 (white)** → no relationship
# - **-1.0 (dark red)** → as one goes up, the other goes down

# We only include columns that are meaningful to correlate — we drop `id` and `year` since they're identifiers, not measurements.

# Column names are rotated so they don't overlap. `annot=True` prints the actual correlation number inside each cell.
# """

# # Select only meaningful numeric columns
# drop_cols = ['id', 'year']
# numeric_df = df.select_dtypes(include='number').drop(columns=drop_cols, errors='ignore')

# corr = numeric_df.corr()

# fig, ax = plt.subplots(figsize=(16, 13))

# sns.heatmap(
#     corr,
#     annot=True,
#     fmt='.2f',
#     cmap='coolwarm',
#     center=0,
#     linewidths=0.4,
#     linecolor='white',
#     annot_kws={'size': 7},    # annotation font size inside cells
#     square=True,
#     cbar_kws={'shrink': 0.75, 'label': 'Correlation coefficient'},
#     ax=ax
# )

# ax.set_title('Correlation Heatmap — All Numeric Features', pad=16)

# # Rotate x-axis labels 45° and align them under the columns
# ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', fontsize=8)
# ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=8)

# plt.tight_layout()
# # plt.savefig('chart10_correlation_heatmap.png', bbox_inches='tight')
# plt.show()

# """---
# ## Bonus — All 10 charts as one dashboard

# This cell renders a compact **2-column grid** of all charts side by side — useful for a quick overview or to export as a single summary image.

# Each subplot reuses the same logic as above. `plt.suptitle` adds a master title above the whole grid, with `y=1.01` nudging it up so it doesn't overlap the top row.
# """

# exp_order_present = [e for e in EXP_ORDER if e in df['experience_level'].unique()]
# size_order = [s for s in ['Small', 'Medium', 'Large'] if s in df['company_size'].unique()]

# fig = plt.figure(figsize=(20, 36))
# fig.suptitle('Tech Jobs Dataset — Visual Summary', fontsize=18, fontweight='bold', y=1.005)

# # ── 1. Salary histogram ────────────────────────────────────
# ax1 = fig.add_subplot(5, 2, 1)
# ax1.hist(df['salary_usd'], bins=50, color='steelblue', edgecolor='white', linewidth=0.3)
# ax1.axvline(df['salary_usd'].mean(),   color='tomato',     linestyle='--', linewidth=1.2, label='Mean')
# ax1.axvline(df['salary_usd'].median(), color='darkorange', linestyle='--', linewidth=1.2, label='Median')
# ax1.set_title('Salary Distribution')
# ax1.set_xlabel('Salary (USD)')
# ax1.set_ylabel('Count')
# ax1.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
# ax1.legend(fontsize=8)

# # ── 2. Salary by experience ────────────────────────────────
# ax2 = fig.add_subplot(5, 2, 2)
# sns.boxplot(data=df, x='experience_level', y='salary_usd', order=exp_order_present,
#             palette='Blues', width=0.5, flierprops=dict(marker='o', markersize=1, alpha=0.2), ax=ax2)
# ax2.set_title('Salary by Experience Level')
# ax2.set_xlabel('Experience Level')
# ax2.set_ylabel('Salary (USD)')
# ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

# # ── 3. Salary by work mode ─────────────────────────────────
# ax3 = fig.add_subplot(5, 2, 3)
# sns.boxplot(data=df, x='work_mode', y='salary_usd', palette='Set2',
#             width=0.45, flierprops=dict(marker='o', markersize=1, alpha=0.2), ax=ax3)
# ax3.set_title('Salary by Work Mode')
# ax3.set_xlabel('Work Mode')
# ax3.set_ylabel('Salary (USD)')
# ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

# # ── 4. Top 5 countries by job count ──────────────────────
# ax4 = fig.add_subplot(5, 2, 4)
# top_c = df['country'].value_counts().head(10)
# ax4.bar(top_c.index, top_c.values, color=sns.color_palette('muted', 15), edgecolor='white', linewidth=0.3)
# ax4.set_title('Top 15 Countries by Job Count')
# ax4.set_xlabel('Country')
# ax4.set_ylabel('Jobs')
# ax4.set_xticklabels(top_c.index, rotation=45, ha='right', fontsize=7)
# ax4.set_ylim(0, top_c.max() * 1.1)

# # ── 5. Avg salary by country ───────────────────────────────
# ax5 = fig.add_subplot(5, 2, 5)
# avg_sc = df.groupby('country')['salary_usd'].mean().sort_values(ascending=False).head(10)
# ax5.barh(avg_sc.index[::-1], avg_sc.values[::-1],
#          color=sns.color_palette('Blues_r', 15), edgecolor='white', linewidth=0.3)
# ax5.set_title('Top 15 Countries by Avg Salary')
# ax5.set_xlabel('Avg Salary (USD)')
# ax5.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
# ax5.tick_params(axis='y', labelsize=7)

# # ── 6. Job role distribution ───────────────────────────────
# ax6 = fig.add_subplot(5, 2, 6)
# rc = df['job_role'].value_counts().sort_values()
# ax6.barh(rc.index, rc.values, color=sns.color_palette('viridis', len(rc)), edgecolor='white', linewidth=0.3)
# ax6.set_title('Job Role Distribution')
# ax6.set_xlabel('Count')
# ax6.tick_params(axis='y', labelsize=7)

# # ── 7. Salary by company size ──────────────────────────────
# ax7 = fig.add_subplot(5, 2, 7)
# sns.boxplot(data=df, x='company_size', y='salary_usd', order=size_order,
#             palette='Purples', width=0.45, flierprops=dict(marker='o', markersize=1, alpha=0.2), ax=ax7)
# ax7.set_title('Salary by Company Size')
# ax7.set_xlabel('Company Size')
# ax7.set_ylabel('Salary (USD)')
# ax7.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

# # ── 8. Hiring trends over time ─────────────────────────────
# ax8 = fig.add_subplot(5, 2, 8)
# yearly = df.groupby('year').agg(job_count=('id','count'), avg_salary=('salary_usd','mean')).reset_index()
# ax8.plot(yearly['year'], yearly['job_count'], color='steelblue', marker='o', linewidth=1.8, markersize=5)
# ax8b = ax8.twinx()
# ax8b.plot(yearly['year'], yearly['avg_salary'], color='tomato', marker='s', linewidth=1.8,
#           markersize=5, linestyle='--')
# ax8.set_title('Job Count & Avg Salary by Year')
# ax8.set_xlabel('Year')
# ax8.set_ylabel('Job Count', color='steelblue', fontsize=8)
# ax8b.set_ylabel('Avg Salary', color='tomato', fontsize=8)
# ax8b.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
# ax8.set_xticks(yearly['year'])

# # ── 9. Work mode donut ─────────────────────────────────────
# ax9 = fig.add_subplot(5, 2, 9)
# wmc = df['work_mode'].value_counts()
# wedges, texts, autotexts = ax9.pie(
#     wmc.values, labels=wmc.index, autopct='%1.1f%%',
#     colors=sns.color_palette('Set2', len(wmc)),
#     wedgeprops=dict(width=0.45, edgecolor='white', linewidth=1.5),
#     startangle=90, pctdistance=0.78, labeldistance=1.12
# )
# for t in texts: t.set_fontsize(8)
# for at in autotexts: at.set_fontsize(7.5); at.set_color('white'); at.set_fontweight('bold')
# ax9.set_title('Work Mode Split')

# # ── 10. Correlation heatmap ────────────────────────────────
# ax10 = fig.add_subplot(5, 2, (9, 10))  # spans both columns in last row
# numeric_df = df.select_dtypes(include='number').drop(columns=['id','year'], errors='ignore')
# sns.heatmap(
#     numeric_df.corr(), annot=True, fmt='.1f', cmap='coolwarm', center=0,
#     linewidths=0.3, annot_kws={'size': 6}, square=True,
#     cbar_kws={'shrink': 0.6}, ax=ax10
# )
# ax10.set_title('Correlation Heatmap — All Numeric Features', pad=12)
# ax10.set_xticklabels(ax10.get_xticklabels(), rotation=45, ha='right', fontsize=7)
# ax10.set_yticklabels(ax10.get_yticklabels(), rotation=0, fontsize=7)

# plt.tight_layout(h_pad=3.5, w_pad=2.5)
# # plt.savefig('tech_jobs_dashboard.png', bbox_inches='tight', dpi=150)
# plt.show()
# # print('Dashboard saved as tech_jobs_dashboard.png')
import pandas as pd
import matplotlib.pyplot as plt
import matplotlib.ticker as mticker
import seaborn as sns
import streamlit as st

# ── 1. PAGE CONFIGURATION ───────────────────────────────────
st.set_page_config(
    page_title="Tech Jobs Dashboard",
    page_icon="📊",
    layout="wide"
)

st.title("📊 Tech Jobs Dataset — Visualizations")
st.markdown("""
Now that we've explored the raw data, it's time to **see** it. Charts reveal patterns that numbers alone can't show — skewed distributions, outliers, clear category gaps.
""")

# ── 2. CACHED DATA LOADING ──────────────────────────────────
@st.cache_data
@st.cache_data
def load_data():
    df = pd.read_csv('global_ai_jobs.csv') 
    return df

try:
    df = load_data()
except Exception as e:
    st.error(f"Gagal memuat data dari Google Drive: {e}")
    st.stop()

# ── 3. GLOBAL PLOT STYLE ────────────────────────────────────
sns.set_theme(style='whitegrid', palette='muted')

plt.rcParams.update({
    'figure.figsize'     : (12, 5),   # default chart size
    'figure.dpi'         : 120,        # sharp rendering
    'axes.titlesize'     : 14,         # chart title font size
    'axes.titlepad'      : 14,         # gap between title and chart
    'axes.labelsize'     : 11,         # axis label font size
    'axes.labelpad'      : 8,          # gap between axis label and ticks
    'xtick.labelsize'    : 9,          # x-axis tick font size
    'ytick.labelsize'    : 9,          # y-axis tick font size
    'legend.fontsize'    : 9,
    'figure.titlesize'   : 15,
})

EXP_ORDER = ['Entry', 'Mid', 'Senior', 'Lead']
COMP_SIZE = ['Startup', 'Small', 'Medium', 'Large', 'Enterprise']

# ── 4. STREAMLIT TABS STRUCTURE ──────────────────────────────
# Membuat tab untuk ringkasan dashboard utama dan masing-masing grafik individu
tabs = st.tabs([
    "🎯 Full Dashboard", 
    "1. Salary Histogram", 
    "2. Salary by Experience", 
    "3. Salary by Work Mode", 
    "4. Top Countries", 
    "5. Avg Salary by Country", 
    "6. Job Roles", 
    "7. Salary by Company Size", 
    "8. Hiring Trends", 
    "9. Work Mode Split", 
    "10. Correlation Heatmap"
])

# ── TAB: BONUS ALL-IN-ONE DASHBOARD ──────────────────────────
with tabs[0]:
    st.header("All 10 Charts as One Dashboard")
    st.markdown("This grid renders a compact 2-column view of all charts side by side.")
    
    exp_order_present = [e for e in EXP_ORDER if e in df['experience_level'].unique()]
    size_order = [s for s in ['Small', 'Medium', 'Large'] if s in df['company_size'].unique()]

    fig = plt.figure(figsize=(20, 36))
    fig.suptitle('Tech Jobs Dataset — Visual Summary', fontsize=18, fontweight='bold', y=1.005)

    # 1. Salary histogram
    ax1 = fig.add_subplot(5, 2, 1)
    ax1.hist(df['salary_usd'], bins=50, color='steelblue', edgecolor='white', linewidth=0.3)
    ax1.axvline(df['salary_usd'].mean(),   color='tomato',     linestyle='--', linewidth=1.2, label='Mean')
    ax1.axvline(df['salary_usd'].median(), color='darkorange', linestyle='--', linewidth=1.2, label='Median')
    ax1.set_title('Salary Distribution')
    ax1.set_xlabel('Salary (USD)')
    ax1.set_ylabel('Count')
    ax1.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    ax1.legend(fontsize=8)

    # 2. Salary by experience
    ax2 = fig.add_subplot(5, 2, 2)
    sns.boxplot(data=df, x='experience_level', y='salary_usd', order=exp_order_present,
                palette='Blues', width=0.5, flierprops=dict(marker='o', markersize=1, alpha=0.2), ax=ax2)
    ax2.set_title('Salary by Experience Level')
    ax2.set_xlabel('Experience Level')
    ax2.set_ylabel('Salary (USD)')
    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

    # 3. Salary by work mode
    ax3 = fig.add_subplot(5, 2, 3)
    sns.boxplot(data=df, x='work_mode', y='salary_usd', palette='Set2',
                width=0.45, flierprops=dict(marker='o', markersize=1, alpha=0.2), ax=ax3)
    ax3.set_title('Salary by Work Mode')
    ax3.set_xlabel('Work Mode')
    ax3.set_ylabel('Salary (USD)')
    ax3.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

    # 4. Top 5 countries
    ax4 = fig.add_subplot(5, 2, 4)
    top_c = df['country'].value_counts().head(5)
    ax4.bar(top_c.index, top_c.values, color=sns.color_palette('muted', 5), edgecolor='white', linewidth=0.3)
    ax4.set_title('Top 5 Countries by Job Count')
    ax4.set_xlabel('Country')
    ax4.set_ylabel('Jobs')
    ax4.set_xticks(range(len(top_c.index)))
    ax4.set_xticklabels(top_c.index, rotation=45, ha='right', fontsize=7)
    ax4.set_ylim(0, top_c.max() * 1.1)

    # 5. Avg salary by country
    ax5 = fig.add_subplot(5, 2, 5)
    avg_sc = df.groupby('country')['salary_usd'].mean().sort_values(ascending=False).head(10)
    ax5.barh(avg_sc.index[::-1], avg_sc.values[::-1],
             color=sns.color_palette('Blues_r', 10), edgecolor='white', linewidth=0.3)
    ax5.set_title('Top 10 Countries by Avg Salary')
    ax5.set_xlabel('Avg Salary (USD)')
    ax5.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    ax5.tick_params(axis='y', labelsize=7)

    # 6. Job role distribution
    ax6 = fig.add_subplot(5, 2, 6)
    rc = df['job_role'].value_counts().sort_values()
    ax6.barh(rc.index, rc.values, color=sns.color_palette('viridis', len(rc)), edgecolor='white', linewidth=0.3)
    ax6.set_title('Job Role Distribution')
    ax6.set_xlabel('Count')
    ax6.tick_params(axis='y', labelsize=7)

    # 7. Salary by company size
    ax7 = fig.add_subplot(5, 2, 7)
    sns.boxplot(data=df, x='company_size', y='salary_usd', order=size_order,
                palette='Purples', width=0.45, flierprops=dict(marker='o', markersize=1, alpha=0.2), ax=ax7)
    ax7.set_title('Salary by Company Size')
    ax7.set_xlabel('Company Size')
    ax7.set_ylabel('Salary (USD)')
    ax7.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))

    # 8. Hiring trends
    ax8 = fig.add_subplot(5, 2, 8)
    yearly_df = df.groupby('year').agg(job_count=('id','count'), avg_salary=('salary_usd','mean')).reset_index()
    ax8.plot(yearly_df['year'], yearly_df['job_count'], color='steelblue', marker='o', linewidth=1.8, markersize=5)
    ax8b = ax8.twinx()
    ax8b.plot(yearly_df['year'], yearly_df['avg_salary'], color='tomato', marker='s', linewidth=1.8,
              markersize=5, linestyle='--')
    ax8.set_title('Job Count & Avg Salary by Year')
    ax8.set_xlabel('Year')
    ax8.set_ylabel('Job Count', color='steelblue', fontsize=8)
    ax8b.set_ylabel('Avg Salary', color='tomato', fontsize=8)
    ax8b.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    ax8.set_xticks(yearly_df['year'])

    # 9. Work mode donut
    ax9 = fig.add_subplot(5, 2, 9)
    wmc = df['work_mode'].value_counts()
    wedges, texts, autotexts = ax9.pie(
        wmc.values, labels=wmc.index, autopct='%1.1f%%',
        colors=sns.color_palette('Set2', len(wmc)),
        wedgeprops=dict(width=0.45, edgecolor='white', linewidth=1.5),
        startangle=90, pctdistance=0.78, labeldistance=1.12
    )
    for t in texts: t.set_fontsize(8)
    for at in autotexts: at.set_fontsize(7.5); at.set_color('white'); at.set_fontweight('bold')
    ax9.set_title('Work Mode Split')

    # 10. Correlation heatmap
    ax10 = fig.add_subplot(5, 2, 10)
    numeric_df = df.select_dtypes(include='number').drop(columns=['id','year'], errors='ignore')
    sns.heatmap(
        numeric_df.corr(), annot=True, fmt='.2f', cmap='coolwarm', center=0,
        linewidths=0.3, annot_kws={'size': 7}, square=True,
        cbar_kws={'shrink': 0.6}, ax=ax10
    )
    ax10.set_title('Correlation Heatmap', pad=12)
    ax10.set_xticklabels(ax10.get_xticklabels(), rotation=45, ha='right', fontsize=7)
    ax10.set_yticklabels(ax10.get_yticklabels(), rotation=0, fontsize=7)

    plt.tight_layout(h_pad=3.5, w_pad=2.5)
    st.pyplot(fig)


# ── TAB 1: SALARY DISTRIBUTION ──────────────────────────────
with tabs[1]:
    st.header("Chart 1 — Salary distribution (histogram)")
    st.markdown("""
    A histogram groups salaries into buckets and shows how many records fall in each. This reveals:
    - Whether most jobs cluster around a common salary
    - Whether the distribution is symmetric or skewed right (long tail of very high earners)
    - Any unusual gaps or spikes
    
    The vertical dashed lines mark the **mean** and **median** — if they're far apart, the data is skewed.
    """)
    
    fig, ax = plt.subplots(figsize=(12, 5))
    ax.hist(df['salary_usd'], bins=60, color='steelblue', edgecolor='white', linewidth=0.4)
    
    mean_sal   = df['salary_usd'].mean()
    median_sal = df['salary_usd'].median()
    
    ax.axvline(mean_sal,   color='tomato',   linestyle='--', linewidth=1.5, label=f'Mean   ${mean_sal:,.0f}')
    ax.axvline(median_sal, color='darkorange',  linestyle='--', linewidth=1.5, label=f'Median ${median_sal:,.0f}')
    
    ax.set_title('Salary Distribution Across All Tech Jobs')
    ax.set_xlabel('Salary (USD)')
    ax.set_ylabel('Number of Jobs')
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    ax.legend(framealpha=0.9)
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 2: SALARY BY EXPERIENCE ──────────────────────────────
with tabs[2]:
    st.header("Chart 2 — Salary by experience level (boxplot)")
    st.markdown("A boxplot summarises the full salary range at each experience level in one shape.")
    
    exp_order_present = [e for e in EXP_ORDER if e in df['experience_level'].unique()]
    
    fig, ax = plt.subplots(figsize=(10, 5))
    sns.boxplot(
        data=df, x='experience_level', y='salary_usd', order=exp_order_present,
        palette='Blues', width=0.5, flierprops=dict(marker='o', markersize=2, alpha=0.3), ax=ax
    )
    ax.set_title('Salary by Experience Level')
    ax.set_xlabel('Experience Level')
    ax.set_ylabel('Salary (USD)')
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 3: SALARY BY WORK MODE ───────────────────────────────
with tabs[3]:
    st.header("Chart 3 — Salary by work mode (boxplot)")
    st.markdown("**Do remote workers earn more?** This chart compares salary distributions across Remote, Hybrid, and Onsite roles side by side.")
    
    fig, ax = plt.subplots(figsize=(9, 5))
    sns.boxplot(
        data=df, x='work_mode', y='salary_usd', palette='Set2',
        width=0.45, flierprops=dict(marker='o', markersize=1.5, alpha=0.2), ax=ax
    )
    ax.set_title('Salary by Work Mode (Remote vs Hybrid vs Onsite)')
    ax.set_xlabel('Work Mode')
    ax.set_ylabel('Salary (USD)')
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 4: TOP COUNTRIES BY JOB COUNT ────────────────────────
with tabs[4]:
    st.header("Chart 4 — Top 5 countries by job count (bar chart)")
    st.markdown("Which countries contribute the most records to this dataset?")
    
    top_countries = df['country'].value_counts().head()
    
    fig, ax = plt.subplots(figsize=(10, 5))
    bars = ax.bar(top_countries.index, top_countries.values, color=sns.color_palette('muted', 5), edgecolor='white', linewidth=0.5)
    
    for bar in bars:
        h = bar.get_height()
        ax.text(bar.get_x() + bar.get_width() / 2, h + 50, f'{h:,}', ha='center', va='bottom', fontsize=7.5)
        
    ax.set_title('Top 5 Countries by Number of Job Records')
    ax.set_xlabel('Country')
    ax.set_ylabel('Number of Jobs')
    ax.set_xticks(range(len(top_countries.index)))
    ax.set_xticklabels(top_countries.index, rotation=45, ha='right', fontsize=9)
    ax.set_ylim(0, top_countries.max() * 1.12)
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 5: AVERAGE SALARY BY COUNTRY ─────────────────────────
with tabs[5]:
    st.header("Chart 5 — Average salary by country, top 10 (horizontal bar)")
    st.markdown("We use a **horizontal bar chart** here because country names are long — placing them on the y-axis avoids any rotation.")
    
    avg_salary_country = df.groupby('country')['salary_usd'].mean().sort_values(ascending=False).head(10)
    
    fig, ax = plt.subplots(figsize=(11, 6))
    colors = sns.color_palette('Blues_r', len(avg_salary_country))
    bars = ax.barh(avg_salary_country.index[::-1], avg_salary_country.values[::-1], color=colors, edgecolor='white', linewidth=0.4)
    
    for bar, val in zip(bars, avg_salary_country.values[::-1]):
        ax.text(val + 400, bar.get_y() + bar.get_height() / 2, f'${val:,.0f}', va='center', fontsize=8)
        
    ax.set_title('Top 10 Countries by Average Salary (USD)')
    ax.set_xlabel('Average Salary (USD)')
    ax.set_ylabel('')
    ax.xaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    ax.set_xlim(0, avg_salary_country.max() * 1.12)
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 6: JOB ROLE DISTRIBUTION ─────────────────────────────
with tabs[6]:
    st.header("Chart 6 — Job role distribution (horizontal bar)")
    st.markdown("How are jobs distributed across roles like Data Scientist, ML Engineer, Software Engineer?")
    
    role_counts = df['job_role'].value_counts().sort_values(ascending=True)
    
    fig, ax = plt.subplots(figsize=(11, max(5, len(role_counts) * 0.45)))
    colors = sns.color_palette('viridis', len(role_counts))
    bars = ax.barh(role_counts.index, role_counts.values, color=colors, edgecolor='white', linewidth=0.4)
    
    for bar, val in zip(bars, role_counts.values):
        ax.text(val + 30, bar.get_y() + bar.get_height() / 2, f'{val:,}', va='center', fontsize=8)
        
    ax.set_title('Job Count by Role')
    ax.set_xlabel('Number of Job Records')
    ax.set_ylabel('')
    ax.set_xlim(0, role_counts.max() * 1.10)
    plt.subplots_adjust(left=0.28)
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 7: SALARY BY COMPANY SIZE ────────────────────────────
with tabs[7]:
    st.header("Chart 7 — Salary by company size (boxplot)")
    st.markdown("Do large corporations pay more than startups? This boxplot compares salary ranges.")
    
    size_order = [s for s in ['Small', 'Medium', 'Large'] if s in df['company_size'].unique()]
    
    fig, ax = plt.subplots(figsize=(9, 5))
    sns.boxplot(
        data=df, x='company_size', y='salary_usd', order=size_order, palette='Purples',
        width=0.45, flierprops=dict(marker='o', markersize=1.5, alpha=0.2), ax=ax
    )
    ax.set_title('Salary by Company Size')
    ax.set_xlabel('Company Size')
    ax.set_ylabel('Salary (USD)')
    ax.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 8: HIRING TRENDS OVER TIME ───────────────────────────
with tabs[8]:
    st.header("Chart 8 — Hiring trends over time (line chart)")
    st.markdown("How has the number of tech job records changed from 2020 to 2026?")
    
    yearly = df.groupby('year').agg(job_count=('id', 'count'), avg_salary=('salary_usd', 'mean')).reset_index()
    
    fig, ax1 = plt.subplots(figsize=(11, 5))
    color1 = 'steelblue'
    ax1.plot(yearly['year'], yearly['job_count'], color=color1, marker='o', linewidth=2, markersize=6, label='Job count')
    ax1.fill_between(yearly['year'], yearly['job_count'], alpha=0.12, color=color1)
    ax1.set_xlabel('Year')
    ax1.set_ylabel('Number of Job Records', color=color1, labelpad=8)
    ax1.tick_params(axis='y', labelcolor=color1)
    ax1.set_xticks(yearly['year'])
    
    ax2 = ax1.twinx()
    color2 = 'tomato'
    ax2.plot(yearly['year'], yearly['avg_salary'], color=color2, marker='s', linewidth=2, markersize=6, linestyle='--', label='Avg salary')
    ax2.set_ylabel('Average Salary (USD)', color=color2, labelpad=8)
    ax2.tick_params(axis='y', labelcolor=color2)
    ax2.yaxis.set_major_formatter(mticker.FuncFormatter(lambda x, _: f'${x/1000:.0f}k'))
    
    lines1, labels1 = ax1.get_legend_handles_labels()
    lines2, labels2 = ax2.get_legend_handles_labels()
    ax1.legend(lines1 + lines2, labels1 + labels2, loc='upper left', framealpha=0.9)
    
    ax1.set_title('Tech Job Count and Average Salary by Year (2020–2026)')
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 9: WORK MODE BREAKDOWN ───────────────────────────────
with tabs[9]:
    st.header("Chart 9 — Work mode breakdown (donut chart)")
    st.markdown("What percentage of jobs are Remote vs Hybrid vs Onsite?")
    
    work_mode_counts = df['work_mode'].value_counts()
    
    fig, ax = plt.subplots(figsize=(7, 6))
    wedge_props = dict(width=0.45, edgecolor='white', linewidth=2)
    wedges, texts, autotexts = ax.pie(
        work_mode_counts.values, labels=work_mode_counts.index, autopct='%1.1f%%',
        startangle=90, colors=sns.color_palette('Set2', len(work_mode_counts)),
        wedgeprops=wedge_props, pctdistance=0.78, labeldistance=1.12
    )
    
    for text in texts: text.set_fontsize(10)
    for autotext in autotexts:
        autotext.set_fontsize(9)
        autotext.set_color('white')
        autotext.set_fontweight('bold')
        
    ax.set_title('Work Mode Distribution\n(Remote vs Hybrid vs Onsite)', pad=18)
    plt.tight_layout()
    st.pyplot(fig)


# ── TAB 10: CORRELATION HEATMAP ──────────────────────────────
with tabs[10]:
    st.header("Chart 10 — Correlation heatmap")
    st.markdown("A heatmap shows how pairs of numeric columns **move together**.")
    
    drop_cols = ['id', 'year']
    numeric_df = df.select_dtypes(include='number').drop(columns=drop_cols, errors='ignore')
    corr = numeric_df.corr()
    
    fig, ax = plt.subplots(figsize=(10, 8))
    sns.heatmap(
        corr, annot=True, fmt='.2f', cmap='coolwarm', center=0,
        linewidths=0.4, linecolor='white', annot_kws={'size': 8}, square=True,
        cbar_kws={'shrink': 0.75, 'label': 'Correlation coefficient'}, ax=ax
    )
    ax.set_title('Correlation Heatmap — All Numeric Features', pad=16)
    ax.set_xticklabels(ax.get_xticklabels(), rotation=45, ha='right', fontsize=8)
    ax.set_yticklabels(ax.get_yticklabels(), rotation=0, fontsize=8)
    plt.tight_layout()
    st.pyplot(fig)